#!/bin/sh



if [[ $2 == prod ]]

then

echo 'Downloading minilims...'

wget -nv -O .minilims http://htsstation.epfl.ch/$1/data/$1_minilims

elif [[ $2 == dev ]]

then

echo 'Downloading minilims...'

wget -nv -O .minilims http://dev.htsstation.vital-it.ch/$1/data/$1_minilims

else

echo 'USAGE: ./readminilims [mapseq|chipseq|demultiplexing|snp|rnaseq|4cseq] [dev|prod]'

exit 0

fi

sqlite3 .minilims