#!/bin/bash

# Realign the reads generated by FluxSimulator on the reference genome with Bowtie2.

if [ $# -lt 1 ]
then
  echo "Usage: $0 <md5>"
  exit
fi

# bowtie2 [options]* -x <bt2-idx> {-1 <m1> -2 <m2> | -U <r>} [-S <sam>]
md5=$1
job='realign'
path1='bowtie'
bsub -J $job -e logs/${job}.err -o logs/${job}.out -M 15000000 -R "rusage[mem=15000] span[ptile=4]" " \
    bowtie2 --local --sensitive-local -k 20 --threads 4 \
    --un-gz $path1/unaligned.fastq.gz --un-conc-gz $path1/unaligned_pairs.fastq.gz \
    -x /db/genrep/nr_assemblies/bowtie2/$md5 \
    -U simulation.fastq \
    -S $path1/realignment.sam
"

