#!/bin/bash

# Realign the reads generated by FluxSimulator on the reference genome with Bowtie2.

if [ $# -lt 1 ]
then
  echo "Usage: $0 <md5> <gtf>"
  exit
fi

md5=$1
gtf=$2
job='realign_tophat'
bsub -J $job -e logs/${job}.err -o logs/${job}.out -M 15000000 -R "rusage[mem=15000] span[ptile=6]" " \
    tophat -p 6 -g 1 --no-novel-juncs --no-novel-indels --b2-very-sensitive -G $gtf  \
    --transcriptome-index tophat/index/trx  \
    -o tophat \
    tophat/index/$md5 \
    ./simulation.fastq
"
